### ISSUE TITLE
consistance dans les dates suite et fin

### ISSUE THREAD

**Issue by LePetitMarill** [hadware/loult-ng#11]
Est il possible d'avoir un msg.date pour les msg.type "connect", "disconnect", ainsi qu'avec "backlog" svp mr le pr

D'ailleurs on reçoit "backlog" et "userlist" qu'une seule fois et en meme temps il me semble, peut être serait il habile de les regrouper en un seul truc ? Ou pas hein.

**Comment by hadware** [comment]
We ok pour grouper le backlog et la userlist, ça mange pas de pain. Je vais voir si y'avait pas une raison de simplicité derrière ce choix fait par lombre.

Il me semblait avoir déjà mis les dates sur les connect et les disconnect, t'es sur que ça y est pas?

![capture du 2017-01-26 01-46-36](https://cloud.githubusercontent.com/assets/5477031/22315816/4f87099a-e369-11e6-8e0e-ad73482a632a.png)

**Comment by hadware** [comment]
Chaque message du backlog a une date aussi, d'après le code. Je vais regarder quand même ce que ça donne dans la consolennww

**Comment by hadware** [comment]
A priori c'est déjà bonw aussi pour backlog (et là y'a un ptit connect avec sa datennww aussi)

![image](https://cloud.githubusercontent.com/assets/5477031/22315893/cc743306-e369-11e6-8be5-240e89f8d687.png)
