### ISSUE TITLE
grwe bordel

### ISSUE THREAD

**Issue by PrFeurisson** [hadware/loult-ng#14]
Tu as laissé traîné les restes de ta tentative de subtree dans ton dépôt. Il faudrait que tu repartes de zéro à partir du dépôt de l'elte fwere. J'ai ouvert des issues similaires sur les autres dépôt pas pour t'emmerder mais pour que tout le monde soit au courant aussi vite que possible car après s'il faut rebaser un dépôt qui a été pull par plusieurs personnes ça devient vite infernal.

**Comment by hadware** [comment]
Anw mèwde mèwde mèwde mais normalement ils sont plus là ces machins là non?

**Comment by PrFeurisson** [comment]
Chaque commit dans git pointe vers les commits précédents. Si tu enlèves pas de ton historique les commits qui pointent vers les commits non voulus, ces derniers resterons. Tant que tu merges au lieu de rebase ou de cherry-pick tes commits ne seront jamais modifiés. Mais ici le plus simple c'est juste de remettre ton dépôt à zéro, ou si tu préfères ne pas l'effacer faire `git reset --hard 9e42636` (un vieux commit sans divergence de branches), puis `git pull elte-fwere master` et `git push --force hadware master` (adapte les noms des remotes à ton cas).

**Comment by PrFeurisson** [comment]
Ah il avait pas merge ta pull request. Donc y'a que ton dépôt qui a ce pb.

**Comment by hadware** [comment]
Ouai bon là du coup ça va nan?
