### ISSUE TITLE
Flood et Samples

### ISSUE THREAD

**Issue by Crefwfw** [hadware/loult-ng#4]
Il y aurait moyen qu'une sample ne s'active seulement si la précédente a finis d'être joué ? Car avec des pds comme jr ou mentalw, mon prolordi lagg trop.

**Comment by hadware** [comment]
Wwla. 
Bon déjà c'est le genre de truc coté client que je saurai pas trop faire, mais ça pourrait être utile à une certain point, en reférence à l'issue que j'ai mise sur le dépôt de mrle.

Par contre, et ça je le répète, les sample rajoutés sur les voix **ne ralentissent pas plus ta machine qu'un flood avec du texte et de la voix normale**.

> Eh, jamie, mais comment c'est possible, si y'a de la musique ET de la voix, c'est plus dur pour mon PC non?

Ben nan Fred! Le son que ton PC lit c'est juste une liste de nombre de longueur X qui décrit comment faire vibrer la membrane de ton ampli. Imaginons que je t'envoie le son d'une voix qui lit une très longue phrase de 10 secondes, ça fera `16000 * 10 = 160000` nombres dans la mémoire de ton navigateur. Si j'envoie la même phrase avec un bruit de laser par dessus (we pk pas), mais qui dure tjrs 10 secs, ça fera **toujours** `160000` nombres dans la mémoire de ton navigateur à lire, juste différents parce que c'est pas exactement le même son (**protip** : ton PC s'en branle quand les nombres sont différents).

**Comment by hadware** [comment]
We après par contre je peux ptet envisager un automuter qui détecte le flood coté client. Ça, ça serait bien je pense.

**Comment by Crefwfw** [comment]
Ok, merci pour cette réponse très rapide. C'est pas vraiment la superposition voix + sample qui me pose un problème car en général il spamme du " " mais ils déconnent trop mon ordi est en pls total à chaque fois.

L'automute pourrait vraiment être cwle car quand on fait autre chose à côté on a pas le temps de réagir avant qu'il ne soit trop tard.

**Comment by hadware** [comment]
Ben jvais voir pour mettre une option automute dans le menu, mais c'est 
une truc à faire coté client et chu un peu mauvais en JS.

**Comment by hadware** [comment]
Ben c'est bon ça
